version: "3.5"

services:
  deluge:
    image: edv64/deluge
    build:
      context: .
      args:
        B_DAEMON_PORT: $DAEMON_PORT
        B_WEB_PORT: $WEB_PORT
        B_LISTEN_PORT: $LISTEN_PORT
        B_RPC_LOGIN: $RPC_LOGIN
        B_RPC_PASSWORD: $RPC_PASSWORD
    container_name: deluge
    command: [ "/startup.sh" , "startup" ]
    ports:
      - $DAEMON_PORT:$DAEMON_PORT
      - $WEB_PORT:$WEB_PORT
      - $LISTEN_PORT:$LISTEN_PORT
      - $LISTEN_PORT:$LISTEN_PORT/udp
    volumes:
      - deluge_data:/config
      - /var/log/deluged:/logs
      - /media/store/downloads:/torrent/downloads
      - /media/store/video:/torrent/video
      - /media/store/work:/torrent/work
    restart: unless-stopped
    network_mode: bridge

volumes:
  deluge_data:
#comment if build first
#    external: true
